config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  resource :cart, only: [:update] do
    patch "checkout"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :products, through: :cart_products
  has_many :cart_products

  def add_product(product)
    products << product
  end

  def formatted_total_price_usd
    total_price_in_cents_usd = products.map(&:price_in_cents_usd).reduce(0, :+)
    CurrencyAmount.new(currency: "USD", cents: total_price_in_cents_usd).to_s
  end

  def products_with_quantities
    products.reduce({}) do |products_with_quantities, product|
      if products_with_quantities[product]
        products_with_quantities[product] += 1
      else
        products_with_quantities[product] = 1
      end

      products_with_quantities
    end
  end

  def checkout
    products.clear
  end
end

app/models/cart_product.rb
class CartProduct < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/currency_amount.rb
class CurrencyAmount
  def initialize(currency:, cents:)
    unless currency == "USD"
      fail "Unsupport currency: #{currency}"
    end

    @cents = cents
  end

  def to_s
    sprintf("$%.2f", @cents / 100.0)
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  def formatted_price_usd
    CurrencyAmount.new(currency: "USD", cents: price_in_cents_usd).to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_cart
    return @current_cart if @current_cart.present?

    if session[:cart_id].blank?
      cart = Cart.create!
      session[:cart_id] = cart.id
    else
      cart = Cart.find(session[:cart_id])
    end

    @current_cart = cart
  end
  helper_method :current_cart
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def update
    product = Product.find(cart_params[:product_id])
    cart_params[:quantity].to_i.times do
      current_cart.add_product(product)
    end
    redirect_to :root
  end

  def checkout
    current_cart.checkout
    flash[:notice] = "Purchase complete"
    redirect_to :root
  end

  def cart_params
    params[:cart].permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Donut Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag "donut.png" %>
  </head>

  <body>
    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: name %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>🍩 Donut Shop 🍩</h1>

<h2>Shopping cart</h2>
<div id="cart">
  <p>You have <%= pluralize(current_cart.products.count, "item") %> in your cart:</p>
  <ul>
    <% current_cart.products_with_quantities.each do |product, count| %>
      <li>
        <%= product.name %> (<%= count %>) - <%= product.formatted_price_usd %>
      </li>
    <% end %>
  </ul>
  <p>Total: <%= current_cart.formatted_total_price_usd %></p>
  <p>
    <%= form_for current_cart, url: checkout_cart_path do |f| %>
      <%= f.submit "Checkout" %>
    <% end %>
  </p>
</div>


<h2>Menu</h2>

<ul>
<% @products.each do |product| %>
  <li>
    <div id="product<%= product.id %>">
      <%= product.name %> - <%= product.formatted_price_usd %>
      <%= form_for current_cart, url: cart_path do |f| %>
        <%= f.hidden_field "product_id", value: product.id %>
        <%= f.number_field "quantity", value: 1, min: 1, "aria-label": "Quantity" %>
        <%= f.submit "Add to cart" %>
      <% end %>
    </div>
  </li>
<% end %>
</ul>